image: "python:3.7"

before_script:
  - python --version
  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  - source activate test-environment

script:
  - jupytext "./content/01_data/01_tp_numpy.md" --set-kernel - --execute
